# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  inputs:
    connectedServiceName: "azure-security-live"
    keyVaultName: "live-kv-security-3p"
    secretsFilter: '*'

- script: |
    docker run --rm -v "$(Build.ArtifactStagingDirectory)/output":/app/output -e SNYK_TOKEN=$(SNYK_TOKEN) -e GITHUB_TOKEN=$(GITHUB_TOKEN} -it repo_diff \
               --out-file output/repos-with-no-projects.csv \
               --snyk-group  "4d62001b-9ab4-446a-815c-bf51ea2b129b" \
               --github-org prospa-group
  displayName: 'Run repo-diff'

# publish artifact
- task: PublishBuildArtifacts@1
  displayName: Publish Output to Artifactory
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/output/repos-with-no-projects.csv'
